#! /usr/bin/env bash
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

PROFILE_DIR=$SCRIPT_DIR/archiso-plasma

if [ -d $PROFILE_DIR ]; then
    rm -rf $PROFILE_DIR
fi

mkdir -p $PROFILE_DIR
cp -r /usr/share/archiso/configs/releng/* $PROFILE_DIR

cat $SCRIPT_DIR/plasma-packages >> $PROFILE_DIR/packages.x86_64

ln -s /usr/lib/systemd/system/sddm.service $PROFILE_DIR/airootfs/etc/systemd/system/display-manager.service
ln -s /usr/lib/systemd/system/NetworkManager-wait-online.service $PROFILE_DIR/airootfs/etc/systemd/system/network-online.target.wants/NetworkManager-wait-online.service
ln -s /usr/lib/systemd/system/NetworkManager.service $PROFILE_DIR/airootfs/etc/systemd/system/multi-user.target.wants/NetworkManager.service

rm $PROFILE_DIR/airootfs/etc/systemd/system/multi-user.target.wants/systemd-networkd.service
rm $PROFILE_DIR/airootfs/etc/systemd/system/multi-user.target.wants/systemd-resolved.service
rm $PROFILE_DIR/airootfs/etc/systemd/system/network-online.target.wants/systemd-networkd-wait-online.service

cp -rf $SCRIPT_DIR/pam.d/ $PROFILE_DIR/airootfs/etc/
cp -rf $SCRIPT_DIR/sddm.conf.d/ $PROFILE_DIR/airootfs/etc/
cp $SCRIPT_DIR/auth/* $PROFILE_DIR/airootfs/etc/

mkarchiso -v -w /tmp/archiso-work -o $SCRIPT_DIR/out $PROFILE_DIR

CHOWN_USER=$SUDO_USER

if [ -z "$CHOWN_USER" ]; then
  CHOWN_USER=$USER
fi

chown -R $SUDO_USER:$SUDO_USER $SCRIPT_DIR/out

rm -rf /tmp/archiso-work
rm -rf $PROFILE_DIR