#! /usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

pacman -Syu --noconfirm

pacman -S --noconfirm archiso wezterm-terminfo

mkarchiso -v -w /tmp/archiso-work $SCRIPT_DIR/releng