#! /usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

pacman -Syu --noconfirm

pacman -S --noconfirm archiso ansible

ansible-playbook $SCRIPT_DIR/playbook.yml