#! /usr/bin/bash

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

CHOWN_USER=$SUDO_USER

if [ -z "$CHOWN_USER" ]; then
  CHOWN_USER=$USER
fi

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

mkarchiso -v -w /tmp/archiso-work $SCRIPT_DIR/releng

rm -rf /tmp/archiso-work

chown -R $SUDO_USER:$SUDO_USER $SCRIPT_DIR/out
