name: Build

on:
  schedule:
    - cron: '0 0 * * MON'
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged

    steps:
      - name: Update packages
        run: pacman -Syu --noconfirm

      - name: Install packages
        run: pacman -S --noconfirm git archiso

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build ISO
        run: ./docker-build

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: archlinux-plasma
          path: /build/out/*.iso

  release:
    needs: build
    runs-on: ubuntu-latest
    if: ${{github.ref == 'refs/heads/main'}}

    steps:
    - name: Get Date
      run: echo "VERSION=$(date +'%Y.%m.%d')-${{github.run_attempt}}" > $GITHUB_ENV

    - uses: actions/download-artifact@v4
      with:
        name: archlinux-plasma

    - name: Show downloaded artifacts
      run: ls -R

    - name: Compress ISO
      run: tar czvf archlinux-plasma-$VERSION.tar.gz *.iso
        
    - uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION }}
        files: "*.tar.gz"
        fail_on_unmatched_files: true
        target_commitish: ${{github.sha}}
        generate_release_notes: true
